CREATE TABLE movie(
	movieId INT PRIMARY KEY,
	title TEXT NOT NULL,
	year INT
);

CREATE TABLE genre(
	genreId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genreName TEXT NOT NULL
);

CREATE TABLE app_user(
	userId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT,
	pw TEXT
);

CREATE TABLE movie_genre(
	movieId INT,
	genreId INT,
	PRIMARY KEY (movieId, genreId),
	FOREIGN KEY (movieId) REFERENCES movie(movieId) ON DELETE CASCADE,
	FOREIGN KEY (genreId) REFERENCES genre(genreId) ON DELETE CASCADE
);

CREATE TABLE rating(
	movieId INT,
	userId INT,
	rating SMALLINT NOT NULL,
	recorded_at BIGINT,
	PRIMARY KEY (movieId, userId),
	FOREIGN KEY (movieId) REFERENCES movie(movieId) ON DELETE CASCADE,
	FOREIGN KEY (userId) REFERENCES app_user(userId) ON DELETE CASCADE
);

CREATE TABLE tag(
	tagId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	movieId INT,
	userId INT,
	tag TEXT,
	recorded_at BIGINT,
	FOREIGN KEY (movieId) REFERENCES movie(movieId) ON DELETE CASCADE,
	FOREIGN KEY (userId) REFERENCES app_user(userId) ON DELETE CASCADE
);


-- To run after populating the app_user table:
-- SELECT setval(pg_get_serial_sequence('app_user', 'userid'), (SELECT MAX(userid) FROM app_user));
