CREATE TABLE movie(
	movie_id INT PRIMARY KEY,
	title TEXT NOT NULL,
	year INT
);

CREATE TABLE genre(
	genre_id INT PRIMARY KEY,
	genre_name TEXT NOT NULL
);

CREATE TABLE app_user(
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT,
	pw TEXT
);

-- /!\ After populating the app_user table run:
-- SELECT setval(pg_get_serial_sequence('app_user', 'user_id'), (SELECT MAX(user_id) FROM app_user));

CREATE TABLE movie_genre(
	movie_id INT,
	genre_id INT,
	PRIMARY KEY (movie_id, genre_id),
	FOREIGN KEY (movie_id) REFERENCES movie(movie_id) ON DELETE CASCADE,
	FOREIGN KEY (genre_id) REFERENCES genre(genre_id) ON DELETE CASCADE
);

CREATE TABLE rating(
	movie_id INT,
	user_id INT,
	rating SMALLINT NOT NULL,
	recorded_at BIGINT,
	PRIMARY KEY (movie_id, user_id),
	FOREIGN KEY (movie_id) REFERENCES movie(movie_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

CREATE TABLE tag(
	tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	movie_id INT,
	user_id INT,
	tag TEXT,
	recorded_at BIGINT,
	FOREIGN KEY (movie_id) REFERENCES movie(movie_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);